# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_AdarshSinha_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TestPluginDialogBase(object):
    def setupUi(self, TestPluginDialogBase):
        TestPluginDialogBase.setObjectName("TestPluginDialogBase")
        TestPluginDialogBase.resize(600, 400)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(TestPluginDialogBase)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(TestPluginDialogBase)
        self.label_4.setMinimumSize(QtCore.QSize(200, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(TestPluginDialogBase)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pointFileLineEdit = QtWidgets.QLineEdit(TestPluginDialogBase)
        self.pointFileLineEdit.setObjectName("pointFileLineEdit")
        self.horizontalLayout.addWidget(self.pointFileLineEdit)
        self.pointSelectButton = QtWidgets.QPushButton(TestPluginDialogBase)
        self.pointSelectButton.setObjectName("pointSelectButton")
        self.horizontalLayout.addWidget(self.pointSelectButton)
        self.pointUploadButton = QtWidgets.QPushButton(TestPluginDialogBase)
        self.pointUploadButton.setObjectName("pointUploadButton")
        self.horizontalLayout.addWidget(self.pointUploadButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(TestPluginDialogBase)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineFileLineEdit = QtWidgets.QLineEdit(TestPluginDialogBase)
        self.lineFileLineEdit.setObjectName("lineFileLineEdit")
        self.horizontalLayout_2.addWidget(self.lineFileLineEdit)
        self.lineSelectButton = QtWidgets.QPushButton(TestPluginDialogBase)
        self.lineSelectButton.setObjectName("lineSelectButton")
        self.horizontalLayout_2.addWidget(self.lineSelectButton)
        self.lineUploadButton = QtWidgets.QPushButton(TestPluginDialogBase)
        self.lineUploadButton.setObjectName("lineUploadButton")
        self.horizontalLayout_2.addWidget(self.lineUploadButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(TestPluginDialogBase)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.polygonFileLineEdit = QtWidgets.QLineEdit(TestPluginDialogBase)
        self.polygonFileLineEdit.setObjectName("polygonFileLineEdit")
        self.horizontalLayout_3.addWidget(self.polygonFileLineEdit)
        self.polygonSelectButton = QtWidgets.QPushButton(TestPluginDialogBase)
        self.polygonSelectButton.setObjectName("polygonSelectButton")
        self.horizontalLayout_3.addWidget(self.polygonSelectButton)
        self.polygonUploadButton = QtWidgets.QPushButton(TestPluginDialogBase)
        self.polygonUploadButton.setObjectName("polygonUploadButton")
        self.horizontalLayout_3.addWidget(self.polygonUploadButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.button_box = QtWidgets.QDialogButtonBox(TestPluginDialogBase)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout_2.addWidget(self.button_box)

        self.retranslateUi(TestPluginDialogBase)
        self.button_box.accepted.connect(TestPluginDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(TestPluginDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(TestPluginDialogBase)

    def retranslateUi(self, TestPluginDialogBase):
        _translate = QtCore.QCoreApplication.translate
        TestPluginDialogBase.setWindowTitle(_translate("TestPluginDialogBase", "TEST_AdarshSinha"))
        self.label_4.setText(_translate("TestPluginDialogBase", "Input Files"))
        self.label.setText(_translate("TestPluginDialogBase", "Point File"))
        self.pointFileLineEdit.setPlaceholderText(_translate("TestPluginDialogBase", "(.shp)"))
        self.pointSelectButton.setText(_translate("TestPluginDialogBase", "Select"))
        self.pointUploadButton.setText(_translate("TestPluginDialogBase", "Upload"))
        self.label_2.setText(_translate("TestPluginDialogBase", "Line File"))
        self.lineFileLineEdit.setPlaceholderText(_translate("TestPluginDialogBase", "(.shp)"))
        self.lineSelectButton.setText(_translate("TestPluginDialogBase", "Select"))
        self.lineUploadButton.setText(_translate("TestPluginDialogBase", "Upload"))
        self.label_3.setText(_translate("TestPluginDialogBase", "Polygon File"))
        self.polygonFileLineEdit.setPlaceholderText(_translate("TestPluginDialogBase", "(.shp)"))
        self.polygonSelectButton.setText(_translate("TestPluginDialogBase", "Select"))
        self.polygonUploadButton.setText(_translate("TestPluginDialogBase", "Upload"))
